import React, { useState } from 'react';
import { 
  Video, Play, Sparkles, ArrowRight, CheckCircle2, ChevronDown, 
  ShieldCheck, DollarSign, Search, Music, AlertCircle, HelpCircle, 
  Star, ExternalLink, RefreshCw, Layers 
} from 'lucide-react';

export default function YouTubeContentIdPage({ onNavigate, theme }) {
  const [openFaq, setOpenFaq] = useState(0);
  const [activeGuideTab, setActiveGuideTab] = useState('what-is-cid');

  const CONTENT_ID_FAQS = [
    {
      q: "How does YouTube Content ID work?",
      a: "When you distribute a song through TuneWave and select YouTube Content ID, our system generates a unique digital acoustic fingerprint of your audio recording and submits it to YouTube's master database. Every single video uploaded to YouTube is continuously scanned against this reference file. When a match is detected, an automated monetization claim is placed on your behalf."
    },
    {
      q: "Can I whitelist my own YouTube channel?",
      a: "Yes! If you have your own Official YouTube Channel and want to monetize your videos directly through your own YouTube Partner Program (YPP) or avoid receiving automated copyright claim notices on your own uploads, you can simply submit your channel ID to be added to TuneWave's whitelist."
    },
    {
      q: "What happens when a claim is placed on a fan's video?",
      a: "When Content ID claims a video that uses your song, the video remains visible and playable to the public. Advertisements are placed on the video, and the ad revenue generated by those views is routed directly into your TuneWave account. The creator's channel does not receive a copyright strike."
    },
    {
      q: "What tracks are eligible for YouTube Content ID?",
      a: "To register for YouTube Content ID, you MUST own 100% exclusive rights to both the master recording and underlying composition. Tracks that use non-exclusive beats (leased from sites like BeatStars), royalty-free loops (like GarageBand or Splice packs without exclusive melody clearance), public domain recordings, or ambient nature sounds are strictly ineligible according to YouTube guidelines."
    },
    {
      q: "Can I monetize cover songs with YouTube Content ID?",
      a: "No. Cover songs are not eligible for YouTube Content ID because you do not own exclusive rights to the underlying musical composition written by another songwriter. However, you can still distribute cover songs to streaming platforms like Spotify and Apple Music with a mechanical license."
    },
    {
      q: "How and when do I get paid for YouTube Content ID?",
      a: "YouTube reports and remits advertising revenue on a monthly accounting cycle (typically around 60 days after the close of each calendar month). Once YouTube pays, your earnings appear directly in your TuneWave balance, ready for instant withdrawal."
    }
  ];

  const ROYALTY_BOXES = [
    {
      title: "User-uploaded live performances",
      desc: "Fans capturing your gigs and festival performances on their phones. Monetize every live clip and fan video containing your audio.",
      tag: "CONCERTS & GIGS",
      icon: Music,
      color: "#EF4444"
    },
    {
      title: "Samples of your music in videos",
      desc: "Vloggers, fitness influencers, dance challenge creators, and tutorial makers using your track as background music.",
      tag: "CREATOR VIDEOS & SHORTS",
      icon: Video,
      color: "var(--tw-cyan)"
    },
    {
      title: "Official music and behind-the-scenes",
      desc: "Your official music videos, visualizers, lyric videos, studio vlogs, and acoustic session uploads across YouTube.",
      tag: "OFFICIAL VISUALS",
      icon: Play,
      color: "#38BDF8"
    }
  ];

  const TIMELINE_STEPS = [
    {
      num: "01",
      title: "Register Your Music",
      desc: "Sign up for TuneWave Pro and select YouTube Content ID as a store destination in our Release Builder during upload.",
      badge: "AUDIO FINGERPRINTING"
    },
    {
      num: "02",
      title: "Detection & Matching",
      desc: "YouTube's Content ID system continuously scans billions of hours of video across the entire platform for matching audio.",
      badge: "AUTOMATED SCANNING"
    },
    {
      num: "03",
      title: "Claim Your Royalties",
      desc: "You'll receive 100% of the ad royalties generated from all identified uses of your music on YouTube, paid straight to your balance.",
      badge: "MONTHLY PAYOUTS"
    }
  ];

  const GUIDE_SECTIONS = [
    {
      id: "what-is-cid",
      title: "What is Content ID?",
      content: (
        <div>
          <h4 style={{ fontSize: '1.25rem', fontWeight: 800, color: "var(--tw-text-white)", marginBottom: 12 }}>
            YouTube's Digital Rights Identification System
          </h4>
          <p style={{ color: 'var(--tw-text-dim)', lineHeight: 1.7, marginBottom: 16 }}>
            YouTube Content ID is YouTube's proprietary identification system designed to help artists and copyright owners automatically identify their music and any videos that contain their copyrighted content.
          </p>
          <p style={{ color: 'var(--tw-text-dim)', lineHeight: 1.7 }}>
            Content ID helps protect content owners from copyright infringements by comparing every single video uploaded against an internal database of reference files submitted by certified music partners like TuneWave.
          </p>
        </div>
      )
    },
    {
      id: "what-used-for",
      title: "What is it used for?",
      content: (
        <div>
          <h4 style={{ fontSize: '1.25rem', fontWeight: 800, color: "var(--tw-text-white)", marginBottom: 12 }}>
            Monetizing Every Corner of YouTube
          </h4>
          <p style={{ color: 'var(--tw-text-dim)', lineHeight: 1.7, marginBottom: 16 }}>
            Artists and content creators can use Content ID as a way of monetising their music across the whole of YouTube. If someone is using your songs, you should be getting paid for it.
          </p>
          <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 10, color: '#CBD5E1' }}>
            <li style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <CheckCircle2 size={18} color="#00E5FF" /> Any uploaded live performances by yourself or fans
            </li>
            <li style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <CheckCircle2 size={18} color="#00E5FF" /> Any samples or audio clips appearing across YouTube Shorts
            </li>
            <li style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <CheckCircle2 size={18} color="#00E5FF" /> Fan or officially posted clips from tours, festivals, and DJ sets
            </li>
            <li style={{ display: 'flex', gap: 10, alignItems: 'center' }}>
              <CheckCircle2 size={18} color="#00E5FF" /> Background music in gaming playthroughs, makeup tutorials, and travel vlogs
            </li>
          </ul>
        </div>
      )
    },
    {
      id: "claims-explained",
      title: "What is a Content ID claim?",
      content: (
        <div>
          <h4 style={{ fontSize: '1.25rem', fontWeight: 800, color: "var(--tw-text-white)", marginBottom: 12 }}>
            Automated Monetization, Not a Strike
          </h4>
          <p style={{ color: 'var(--tw-text-dim)', lineHeight: 1.7, marginBottom: 16 }}>
            YouTube Content ID claims are generated automatically whenever someone uploads a video which contains matching audio, no matter how brief a clip. When this happens, you have options:
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))', gap: 14 }}>
            <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)' }}>
              <strong style={{ color: '#00E5FF' }}>1. Monetize the Video</strong>
              <p style={{ fontSize: '0.85rem', color: '#94A3B8', marginTop: 6 }}>
                Ads run on the upload and all generated ad revenue is routed into your TuneWave account. The video stays live.
              </p>
            </div>
            <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)' }}>
              <strong style={{ color: 'var(--tw-cyan)' }}>2. Track Statistics</strong>
              <p style={{ fontSize: '0.85rem', color: '#94A3B8', marginTop: 6 }}>
                Monitor viewership and engagement analytics to see how your music is spreading globally.
              </p>
            </div>
            <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.08)' }}>
              <strong style={{ color: '#EF4444' }}>3. Block If Necessary</strong>
              <p style={{ fontSize: '0.85rem', color: '#94A3B8', marginTop: 6 }}>
                Restrict the video from being viewed if someone blatantly copies your entire unreleased track.
              </p>
            </div>
          </div>
        </div>
      )
    },
    {
      id: "eligibility",
      title: "What is eligible?",
      content: (
        <div>
          <h4 style={{ fontSize: '1.25rem', fontWeight: 800, color: "var(--tw-text-white)", marginBottom: 12 }}>
            Strict Exclusivity Requirements
          </h4>
          <p style={{ color: 'var(--tw-text-dim)', lineHeight: 1.7, marginBottom: 16 }}>
            YouTube takes Content ID integrity seriously. You can only register tracks containing 100% exclusive material:
          </p>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))', gap: 16 }}>
            <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(34, 197, 94, 0.08)', border: '1px solid rgba(34, 197, 94, 0.25)' }}>
              <span style={{ color: '#22C55E', fontWeight: 800, fontSize: '0.82rem' }}>✓ FULLY ELIGIBLE</span>
              <ul style={{ fontSize: '0.85rem', color: '#CBD5E1', marginTop: 8, paddingLeft: 16 }}>
                <li>100% original songs you wrote & recorded</li>
                <li>Exclusive beats you bought with full buyout rights</li>
                <li>Live performance recordings of your own songs</li>
              </ul>
            </div>
            <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(239, 68, 68, 0.08)', border: '1px solid rgba(239, 68, 68, 0.25)' }}>
              <span style={{ color: '#EF4444', fontWeight: 800, fontSize: '0.82rem' }}>✕ NOT ELIGIBLE</span>
              <ul style={{ fontSize: '0.85rem', color: '#CBD5E1', marginTop: 8, paddingLeft: 16 }}>
                <li>Non-exclusive leased beats (BeatStars leases)</li>
                <li>Free/unaltered loops from DAWs or sample packs</li>
                <li>Cover songs, remixes, karaoke, public domain</li>
              </ul>
            </div>
          </div>
        </div>
      )
    }
  ];

  return (
    <div className="youtube-content-id-page" style={{ paddingTop: 30, paddingBottom: 100 }}>
      {/* 1. HERO SECTION */}
      <section style={{ position: 'relative', padding: '40px 0 80px', overflow: 'hidden' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 54, alignItems: 'center' }}>
            <div className="reveal-up">
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 16 }}>
                <span className="pill-badge" style={{ 
                  color: '#EF4444', 
                  background: 'rgba(239, 68, 68, 0.12)', 
                  border: '1px solid rgba(239, 68, 68, 0.3)' 
                }}>
                  <Video size={13} style={{ marginRight: 4 }} />
                  EXCLUSIVE TO TUNEWAVE PRO
                </span>
              </div>

              <h1 style={{
                fontSize: 'clamp(2.5rem, 5.5vw, 4.4rem)',
                fontWeight: 800,
                lineHeight: 1.08,
                marginBottom: 20,
                color: 'var(--tw-text-white)'
              }}>
                YouTube <br />
                <span style={{
                  background: 'linear-gradient(135deg, #EF4444 0%, #F97316 100%)',
                  WebkitBackgroundClip: 'text',
                  WebkitTextFillColor: 'transparent'
                }}>
                  Content ID.
                </span>
              </h1>

              <p style={{
                fontSize: '1.2rem',
                color: 'var(--tw-text-dim)',
                lineHeight: 1.6,
                marginBottom: 36,
                maxWidth: '560px'
              }}>
                Track and protect your music across YouTube. Register songs for Content ID with TuneWave Pro and claim even more royalties from every video, short, and fan upload.
              </p>

              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 16 }}>
                <button 
                  onClick={() => onNavigate('/signup')}
                  className="btn-cyan"
                  style={{
                    padding: '16px 36px',
                    fontSize: '1rem',
                    fontWeight: 700,
                    background: 'linear-gradient(135deg, #EF4444 0%, #B91C1C 100%)',
                    color: "var(--tw-text-white)",
                    border: 'none',
                    boxShadow: '0 12px 30px -8px rgba(239, 68, 68, 0.4)'
                  }}
                >
                  <span>Sign up free</span>
                  <ArrowRight size={18} className="btn-icon-hover" />
                </button>
                <button 
                  onClick={() => onNavigate('/pricing')}
                  className="btn-glass"
                  style={{
                    padding: '16px 30px',
                    fontSize: '1rem',
                    fontWeight: 600
                  }}
                >
                  See pricing →
                </button>
              </div>

              {/* Quick trust metrics */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 24, marginTop: 40, paddingTop: 20, borderTop: '1px solid rgba(255,255,255,0.08)' }}>
                <div>
                  <div style={{ fontSize: '1.3rem', fontWeight: 900, color: '#EF4444' }}>100%</div>
                  <div style={{ fontSize: '0.75rem', color: '#94A3B8' }}>Automated Detection</div>
                </div>
                <div style={{ height: 30, width: 1, background: 'rgba(255,255,255,0.1)' }} />
                <div>
                  <div style={{ fontSize: '1.3rem', fontWeight: 900, color: 'var(--tw-cyan)' }}>2.5Bn+</div>
                  <div style={{ fontSize: '0.75rem', color: '#94A3B8' }}>Monthly YouTube Scans</div>
                </div>
                <div style={{ height: 30, width: 1, background: 'rgba(255,255,255,0.1)' }} />
                <div>
                  <div style={{ fontSize: '1.3rem', fontWeight: 900, color: 'var(--tw-cyan)' }}>0%</div>
                  <div style={{ fontSize: '0.75rem', color: '#94A3B8' }}>Effort Required</div>
                </div>
              </div>
            </div>

            {/* Hero Live Audio Fingerprinting Monitor Card */}
            <div className="reveal-scale">
              <div className="glass-panel card-shimmer-sweep dark-inverted-section" style={{
                borderRadius: 24,
                padding: '36px 32px',
                border: '1px solid rgba(239, 68, 68, 0.3)',
                background: 'radial-gradient(circle at top right, rgba(239, 68, 68, 0.15), #090D15)',
                boxShadow: '0 30px 60px -20px rgba(0, 0, 0, 0.8)'
              }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 24 }}>
                  <div>
                    <div style={{ fontSize: '0.75rem', fontWeight: 800, color: '#EF4444', letterSpacing: '0.1em' }}>
                      YOUTUBE CONTENT ID RADAR
                    </div>
                    <div style={{ fontSize: '1.3rem', fontWeight: 800, color: "#FFFFFF" }}>
                      Audio Fingerprint Matcher
                    </div>
                  </div>
                  <span className="pill-badge" style={{ background: 'rgba(239, 68, 68, 0.15)', color: '#EF4444', borderColor: 'rgba(239, 68, 68, 0.3)' }}>
                    ACTIVE MATCHING
                  </span>
                </div>

                {/* Live Match 1 */}
                <div style={{
                  padding: '18px',
                  borderRadius: 14,
                  background: 'rgba(255, 255, 255, 0.04)',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  marginBottom: 14
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                    <span style={{ fontSize: '0.78rem', fontWeight: 800, color: '#00E5FF' }}>MATCH IDENTIFIED · 100% MONETIZED</span>
                    <span style={{ fontSize: '0.8rem', fontWeight: 800, color: "#FFFFFF" }}>1.4M VIEWS</span>
                  </div>
                  <div style={{ fontSize: '0.98rem', fontWeight: 700, color: "#FFFFFF" }}>Dance Choreography Viral Short</div>
                  <div style={{ fontSize: '0.8rem', color: '#94A3B8', marginTop: 4 }}>Audio match: 0:14 - 0:45. Ad revenue routing to your account.</div>
                </div>

                {/* Live Match 2 */}
                <div style={{
                  padding: '18px',
                  borderRadius: 14,
                  background: 'rgba(255, 255, 255, 0.04)',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  marginBottom: 14
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                    <span style={{ fontSize: '0.78rem', fontWeight: 800, color: 'var(--tw-cyan)' }}>MATCH IDENTIFIED · FAN LIVE CLIP</span>
                    <span style={{ fontSize: '0.8rem', fontWeight: 800, color: "#FFFFFF" }}>380K VIEWS</span>
                  </div>
                  <div style={{ fontSize: '0.98rem', fontWeight: 700, color: "#FFFFFF" }}>London Festival Mainstage Live Set</div>
                  <div style={{ fontSize: '0.8rem', color: '#94A3B8', marginTop: 4 }}>Uploaded by fan. Sound recording verified & claimed.</div>
                </div>

                {/* Live Match 3 */}
                <div style={{
                  padding: '18px',
                  borderRadius: 14,
                  background: 'rgba(255, 255, 255, 0.04)',
                  border: '1px solid rgba(255, 255, 255, 0.08)'
                }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 6 }}>
                    <span style={{ fontSize: '0.78rem', fontWeight: 800, color: '#A78BFA' }}>CREATOR VLOG BACKGROUND</span>
                    <span style={{ fontSize: '0.8rem', fontWeight: 800, color: "#FFFFFF" }}>820K VIEWS</span>
                  </div>
                  <div style={{ fontSize: '0.98rem', fontWeight: 700, color: "#FFFFFF" }}>Travel Vlog: 48 Hours in Tokyo</div>
                  <div style={{ fontSize: '0.8rem', color: '#94A3B8', marginTop: 4 }}>Full chorus used in intro. Royalties added to monthly report.</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 2. SECTION 02 · REGISTER MUSIC FOR YOUTUBE CONTENT ID */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div className="glass-panel card-shimmer-sweep dark-inverted-section" style={{
            borderRadius: 28,
            padding: 'clamp(36px, 6vw, 64px)',
            border: '1px solid rgba(239, 68, 68, 0.35)',
            background: 'linear-gradient(135deg, rgba(239, 68, 68, 0.12) 0%, #090D15 100%)',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: 48,
            alignItems: 'center'
          }}>
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
                <span className="pill-badge" style={{ color: '#EF4444', borderColor: '#EF4444' }}>
                  GLOBAL REACH
                </span>
              </div>

              <h2 style={{
                fontSize: 'clamp(2rem, 4.5vw, 3.2rem)',
                fontWeight: 800,
                lineHeight: 1.15,
                marginBottom: 18,
                color: '#FFFFFF'
              }}>
                Register music for <br />
                <span style={{ color: '#EF4444' }}>YouTube Content ID</span>
              </h2>

              <p style={{ fontSize: '1.15rem', color: '#CBD5E1', lineHeight: 1.65, marginBottom: 28 }}>
                Monetise your music across the entire YouTube platform with Content ID and get paid every time your tracks are featured in any video, short, or live stream.
              </p>

              <button 
                onClick={() => onNavigate('/signup')}
                className="btn-cyan"
                style={{
                  padding: '14px 32px',
                  fontSize: '0.98rem',
                  fontWeight: 700,
                  background: 'linear-gradient(135deg, #EF4444 0%, #B91C1C 100%)',
                  color: "#FFFFFF",
                  border: 'none'
                }}
              >
                <span>Get Started Now</span>
                <ArrowRight size={16} className="btn-icon-hover" />
              </button>
            </div>

            <div className="dark-inverted-section" style={{
              background: '#090D15',
              borderRadius: 20,
              padding: '32px',
              border: '1px solid rgba(255,255,255,0.1)',
              boxShadow: '0 20px 40px rgba(0,0,0,0.5)'
            }}>
              <div style={{ fontSize: '0.78rem', fontWeight: 800, color: 'var(--tw-cyan)', letterSpacing: '0.08em', textTransform: 'uppercase', marginBottom: 14 }}>
                THE CONTENT ID POWER SUITE
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                <div style={{ display: 'flex', gap: 12 }}>
                  <CheckCircle2 size={20} color="#00E5FF" style={{ flexShrink: 0, marginTop: 2 }} />
                  <div>
                    <strong style={{ color: "#FFFFFF", fontSize: '0.95rem' }}>Automated Claim Generation</strong>
                    <p style={{ color: '#94A3B8', fontSize: '0.85rem', marginTop: 2 }}>Zero manual searching. Content ID finds and claims clips in real time.</p>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 12 }}>
                  <CheckCircle2 size={20} color="#00E5FF" style={{ flexShrink: 0, marginTop: 2 }} />
                  <div>
                    <strong style={{ color: "#FFFFFF", fontSize: '0.95rem' }}>YouTube Shorts Monetization</strong>
                    <p style={{ color: '#94A3B8', fontSize: '0.85rem', marginTop: 2 }}>Collect your rightful share of the YouTube Shorts Creator Pool whenever audio is used.</p>
                  </div>
                </div>
                <div style={{ display: 'flex', gap: 12 }}>
                  <CheckCircle2 size={20} color="#00E5FF" style={{ flexShrink: 0, marginTop: 2 }} />
                  <div>
                    <strong style={{ color: "#FFFFFF", fontSize: '0.95rem' }}>Artist Channel Whitelisting</strong>
                    <p style={{ color: '#94A3B8', fontSize: '0.85rem', marginTop: 2 }}>Keep your own artist channel claim-free with instant one-click whitelisting.</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 3. SECTION 03 · WHAT IS YOUTUBE CONTENT ID? (MEDIA CALLOUT LEFT) */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 48, alignItems: 'center' }}>
            {/* Visual Callout */}
            <div className="glass-panel dark-inverted-section" style={{
              borderRadius: 24,
              padding: '36px',
              border: '1px solid rgba(0, 229, 255, 0.25)',
              background: 'linear-gradient(135deg, rgba(0, 126, 167, 0.2), #090D15)',
              boxShadow: '0 20px 40px rgba(0,0,0,0.5)'
            }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
                <div style={{ width: 44, height: 44, borderRadius: 10, background: 'rgba(0, 229, 255, 0.15)', color: '#00E5FF', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                  <Search size={22} />
                </div>
                <h3 style={{ fontSize: '1.25rem', fontWeight: 800, color: "#FFFFFF" }}>How Detection Works</h3>
              </div>
              <p style={{ color: '#CBD5E1', fontSize: '0.92rem', lineHeight: 1.6, marginBottom: 16 }}>
                Every second, over 500 hours of video are uploaded to YouTube. The Content ID algorithm parses every incoming audio track, matching pitch, rhythm, waveforms, and spectrums against your original files.
              </p>
              <div style={{ padding: '14px', borderRadius: 12, background: 'rgba(0,0,0,0.4)', border: '1px solid rgba(255,255,255,0.06)', fontSize: '0.82rem', color: '#00E5FF' }}>
                ✓ Works even if audio is pitched, tempo-shifted, or masked by background noise.
              </div>
            </div>

            {/* Text Copy */}
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
                <span className="pill-badge" style={{ color: 'var(--tw-cyan)', borderColor: 'var(--tw-cyan)' }}>
                  COPYRIGHT PROTECTION
                </span>
              </div>

              <h2 style={{
                fontSize: 'clamp(2rem, 4.5vw, 3.2rem)',
                fontWeight: 800,
                lineHeight: 1.15,
                marginBottom: 18,
                color: 'var(--tw-text-white)'
              }}>
                What is <br />
                <span style={{ color: 'var(--tw-cyan)' }}>YouTube Content ID?</span>
              </h2>

              <p style={{ fontSize: '1.15rem', color: 'var(--tw-text-dim)', lineHeight: 1.65, marginBottom: 20 }}>
                Content ID lets artists claim royalties whenever their copyrighted music appears on YouTube. This means getting paid each time anyone uploads your performances or uses samples of your music in their videos.
              </p>

              <p style={{ fontSize: '0.96rem', color: 'var(--tw-text-dim)', lineHeight: 1.6 }}>
                Instead of issuing manual takedown notices or letting third parties profit from your creative work, Content ID puts revenue generation on complete autopilot.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. SECTION 04 · MID-BANNER: HOW DOES YOUTUBE CONTENT ID WORK? */}
      <section style={{ padding: '60px 0' }}>
        <div className="container">
          <div className="glass-panel card-shimmer-sweep dark-inverted-section" style={{
            borderRadius: 28,
            padding: 'clamp(36px, 6vw, 64px)',
            background: 'linear-gradient(135deg, rgba(0, 229, 255, 0.08) 0%, rgba(9, 13, 21, 0.98) 100%)',
            border: '1px solid rgba(0, 229, 255, 0.25)',
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: 48,
            alignItems: 'center'
          }}>
            <div>
              <h2 style={{
                fontSize: 'clamp(2rem, 4.5vw, 3.2rem)',
                fontWeight: 800,
                lineHeight: 1.15,
                marginBottom: 20,
                color: '#FFFFFF'
              }}>
                How does YouTube <br />
                <span className="text-cyan-gradient">Content ID work?</span>
              </h2>

              <p style={{ fontSize: '1.12rem', color: '#CBD5E1', lineHeight: 1.65, marginBottom: 32 }}>
                YouTube Content ID uses a digital footprint of your music to find it across the platform. As a verified YouTube partner, TuneWave registers your tracks directly with Content ID, ensuring that every upload featuring your music is identified and linked back to your royalty account.
              </p>

              <button 
                onClick={() => onNavigate('/signup')}
                className="btn-cyan"
                style={{
                  padding: '16px 36px',
                  fontSize: '1rem',
                  fontWeight: 700,
                  background: 'linear-gradient(135deg, var(--tw-cyan) 0%, #007EA7 100%)',
                  color: '#090D15',
                  border: 'none',
                  boxShadow: '0 10px 25px -5px rgba(0, 229, 255, 0.4)'
                }}
              >
                <span>Sign up free</span>
                <ArrowRight size={18} className="btn-icon-hover" />
              </button>
            </div>

            <div style={{
              background: 'rgba(0, 0, 0, 0.4)',
              borderRadius: 20,
              padding: '32px',
              border: '1px solid rgba(255, 255, 255, 0.08)'
            }}>
              <h4 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#FFFFFF', marginBottom: 16 }}>
                The 3-Way Advantage:
              </h4>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', borderLeft: '4px solid var(--tw-cyan)' }}>
                  <strong style={{ color: '#FFFFFF' }}>1. Uninterrupted Fans</strong>
                  <p style={{ fontSize: '0.85rem', color: '#94A3B8', marginTop: 4 }}>
                    Fans can freely make dance videos and covers without getting strikes or account bans.
                  </p>
                </div>

                <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', borderLeft: '4px solid #38BDF8' }}>
                  <strong style={{ color: '#38BDF8' }}>2. 100% Monetization</strong>
                  <p style={{ fontSize: '0.85rem', color: '#CBD5E1', marginTop: 4 }}>
                    Every single view generated by that creator now pays ad revenue into your pocket.
                  </p>
                </div>

                <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', borderLeft: '4px solid #A78BFA' }}>
                  <strong style={{ color: '#A78BFA' }}>3. Real-Time Tracking</strong>
                  <p style={{ fontSize: '0.85rem', color: '#CBD5E1', marginTop: 4 }}>
                    See which songs are trending across YouTube creators and where your audience lives.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 5. SECTION 05 · PROTECT YOUR MUSIC & UNLOCK EXTRA ROYALTIES */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: 48, alignItems: 'center' }}>
            <div>
              <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
                <span className="pill-badge" style={{ color: '#EF4444', borderColor: '#EF4444' }}>
                  TUNEWAVE PRO & LABELS
                </span>
              </div>

              <h2 style={{
                fontSize: 'clamp(2rem, 4.5vw, 3.2rem)',
                fontWeight: 800,
                lineHeight: 1.15,
                marginBottom: 18,
                color: 'var(--tw-text-white)'
              }}>
                Protect your music & <br />
                <span style={{ color: '#EF4444' }}>unlock extra royalties</span>
              </h2>

              <p style={{ fontSize: '1.15rem', color: 'var(--tw-text-dim)', lineHeight: 1.65, marginBottom: 28 }}>
                Available to all TuneWave Pro and Label artists, YouTube Content ID can be added to any of your releases within the Release Builder. Content ID automatically launches a claim anytime someone uses your copyrighted content without your permission, safeguarding your work on YouTube.
              </p>

              <button 
                onClick={() => onNavigate('/signup')}
                className="btn-cyan"
                style={{
                  padding: '14px 32px',
                  fontSize: '0.98rem',
                  fontWeight: 700,
                  background: 'linear-gradient(135deg, #EF4444 0%, #B91C1C 100%)',
                  color: "var(--tw-text-white)",
                  border: 'none'
                }}
              >
                <span>Get started</span>
                <ArrowRight size={16} className="btn-icon-hover" />
              </button>
            </div>

            <div className="glass-panel" style={{
              borderRadius: 24,
              padding: '36px',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              background: 'rgba(255, 255, 255, 0.02)'
            }}>
              <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: "var(--tw-text-white)", marginBottom: 16 }}>
                Release Builder Integration:
              </h3>
              <div style={{ padding: '16px', borderRadius: 12, background: 'rgba(239, 68, 68, 0.06)', border: '1px solid rgba(239, 68, 68, 0.2)', marginBottom: 16 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                    <div style={{ width: 14, height: 14, borderRadius: 3, background: '#EF4444', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                      <CheckCircle2 size={12} color="#FFF" />
                    </div>
                    <span style={{ fontWeight: 800, color: "var(--tw-text-white)", fontSize: '0.95rem' }}>YouTube Content ID</span>
                  </div>
                  <span style={{ fontSize: '0.72rem', fontWeight: 800, color: 'var(--tw-cyan)' }}>ACTIVE IN PRO</span>
                </div>
                <p style={{ fontSize: '0.82rem', color: '#94A3B8', marginTop: 8 }}>
                  Checked by default during track submission. Automatic digital fingerprinting upon release.
                </p>
              </div>

              <p style={{ fontSize: '0.88rem', color: 'var(--tw-text-dim)', lineHeight: 1.6 }}>
                Never worry about filling out copyright claim forms or hiring expensive lawyers to track down unauthorized usage. Everything is managed hands-free.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* 6. SECTION 06 · YOUTUBE CONTENT ID EXPLAINED (IN-DEPTH GUIDE TABS) */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div className="reveal-up" style={{ textAlign: 'center', maxWidth: '800px', margin: '0 auto 48px' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <span className="pill-badge" style={{ color: 'var(--tw-cyan)', borderColor: 'var(--tw-cyan)' }}>
                IN-DEPTH MASTERCLASS
              </span>
            </div>
            <h2 style={{
              fontSize: 'clamp(2.2rem, 4.5vw, 3.4rem)',
              fontWeight: 800,
              lineHeight: 1.15,
              marginBottom: 16,
              color: 'var(--tw-text-white)'
            }}>
              YouTube Content ID <span style={{ color: 'var(--tw-cyan)' }}>Explained.</span>
            </h2>
            <p style={{ fontSize: '1.1rem', color: 'var(--tw-text-dim)' }}>
              Explore the rules, rights, and best practices for monetizing your music on YouTube.
            </p>
          </div>

          {/* Guide Tabs */}
          <div style={{ maxWidth: '960px', margin: '0 auto' }}>
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8, justifyContent: 'center', marginBottom: 28 }}>
              {GUIDE_SECTIONS.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveGuideTab(tab.id)}
                  style={{
                    padding: '10px 20px',
                    borderRadius: 10,
                    fontSize: '0.9rem',
                    fontWeight: 700,
                    cursor: 'pointer',
                    transition: 'all 0.2s ease',
                    border: activeGuideTab === tab.id ? '1px solid var(--tw-cyan)' : '1px solid rgba(255,255,255,0.08)',
                    background: activeGuideTab === tab.id ? 'rgba(0, 229, 255, 0.12)' : 'rgba(255,255,255,0.03)',
                    color: activeGuideTab === tab.id ? 'var(--tw-cyan)' : 'var(--tw-text-dim)'
                  }}
                >
                  {tab.title}
                </button>
              ))}
            </div>

            <div className="glass-panel" style={{
              borderRadius: 20,
              padding: 'clamp(28px, 4vw, 44px)',
              border: '1px solid rgba(255, 255, 255, 0.08)',
              background: 'rgba(255, 255, 255, 0.02)'
            }}>
              {GUIDE_SECTIONS.find(s => s.id === activeGuideTab)?.content}
            </div>
          </div>
        </div>
      </section>

      {/* 7. SECTION 07 · PICTURE BOX ROYALTIES GRID */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div className="reveal-up" style={{ textAlign: 'center', maxWidth: '800px', margin: '0 auto 60px' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <span className="pill-badge" style={{ color: '#EF4444', borderColor: '#EF4444' }}>
                WHERE YOU EARN
              </span>
            </div>
            <h2 style={{
              fontSize: 'clamp(2.2rem, 4.5vw, 3.4rem)',
              fontWeight: 800,
              lineHeight: 1.15,
              marginBottom: 16,
              color: 'var(--tw-text-white)'
            }}>
              YouTube Content ID <span style={{ color: '#EF4444' }}>Royalties:</span>
            </h2>
          </div>

          <div className="reveal-stagger" style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
            gap: 28
          }}>
            {ROYALTY_BOXES.map((box, idx) => {
              const IconComp = box.icon;
              return (
                <div 
                  key={idx}
                  className="glass-panel card-shimmer-sweep"
                  style={{
                    borderRadius: 20,
                    padding: '36px 30px',
                    border: '1px solid rgba(255, 255, 255, 0.08)',
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'space-between'
                  }}
                >
                  <div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}>
                      <div style={{
                        width: 48,
                        height: 48,
                        borderRadius: 12,
                        background: 'rgba(255, 255, 255, 0.05)',
                        color: box.color,
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        border: '1px solid rgba(255, 255, 255, 0.1)'
                      }}>
                        <IconComp size={22} />
                      </div>
                      <span style={{
                        fontSize: '0.68rem',
                        fontWeight: 800,
                        letterSpacing: '0.08em',
                        padding: '4px 8px',
                        borderRadius: 6,
                        background: 'rgba(255,255,255,0.05)',
                        color: 'var(--tw-text-dim)'
                      }}>
                        {box.tag}
                      </span>
                    </div>

                    <h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--tw-text-white)', marginBottom: 12 }}>
                      {box.title}
                    </h3>

                    <p style={{ color: 'var(--tw-text-dim)', fontSize: '0.94rem', lineHeight: 1.6 }}>
                      {box.desc}
                    </p>
                  </div>

                  <div style={{ marginTop: 24, paddingTop: 14, borderTop: '1px solid rgba(255,255,255,0.06)', display: 'flex', alignItems: 'center', gap: 6, color: box.color, fontSize: '0.82rem', fontWeight: 700 }}>
                    <CheckCircle2 size={15} /> Auto-Claimed 24/7
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 8. SECTION 08 · 3-STEP TIMELINE */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container">
          <div className="reveal-up" style={{ textAlign: 'center', maxWidth: '800px', margin: '0 auto 64px' }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <span className="pill-badge" style={{ color: 'var(--tw-cyan)', borderColor: 'var(--tw-cyan)' }}>
                HOW IT WORKS
              </span>
            </div>
            <h2 style={{
              fontSize: 'clamp(2.2rem, 4.5vw, 3.4rem)',
              fontWeight: 800,
              lineHeight: 1.15,
              marginBottom: 16,
              color: 'var(--tw-text-white)'
            }}>
              How does YouTube <br />
              <span style={{ color: 'var(--tw-cyan)' }}>Content ID work?</span>
            </h2>
            <p style={{ fontSize: '1.15rem', color: 'var(--tw-text-dim)' }}>
              Making sure your music is protected and identified across YouTube is simple with TuneWave.
            </p>
          </div>

          <div className="reveal-stagger" style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            gap: 28
          }}>
            {TIMELINE_STEPS.map((step, idx) => (
              <div 
                key={idx}
                className="glass-panel card-shimmer-sweep"
                style={{
                  borderRadius: 20,
                  padding: '36px 30px',
                  border: '1px solid rgba(255, 255, 255, 0.08)',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between'
                }}
              >
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 20 }}>
                    <span style={{
                      fontSize: '2rem',
                      fontWeight: 900,
                      color: 'var(--tw-cyan)',
                      fontFamily: 'monospace'
                    }}>
                      {step.num}
                    </span>
                    <span style={{
                      fontSize: '0.68rem',
                      fontWeight: 800,
                      letterSpacing: '0.08em',
                      padding: '4px 8px',
                      borderRadius: 6,
                      background: 'rgba(255,255,255,0.05)',
                      color: 'var(--tw-text-dim)'
                    }}>
                      {step.badge}
                    </span>
                  </div>

                  <h3 style={{ fontSize: '1.3rem', fontWeight: 800, color: 'var(--tw-text-white)', marginBottom: 12 }}>
                    {step.title}
                  </h3>

                  <p style={{ color: 'var(--tw-text-dim)', fontSize: '0.94rem', lineHeight: 1.6 }}>
                    {step.desc}
                  </p>
                </div>

                <div style={{ marginTop: 24, paddingTop: 16, borderTop: '1px solid rgba(255,255,255,0.06)' }}>
                  <span 
                    onClick={() => onNavigate('/signup')}
                    style={{ cursor: 'pointer', color: 'var(--tw-cyan)', fontWeight: 700, fontSize: '0.9rem', display: 'inline-flex', alignItems: 'center', gap: 6 }}
                  >
                    Claim your audio →
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 9. CONTENT ID FAQS */}
      <section style={{ padding: '80px 0', borderTop: '1px solid rgba(255, 255, 255, 0.06)' }}>
        <div className="container" style={{ maxWidth: '880px' }}>
          <div className="reveal-up" style={{ textAlign: 'center', marginBottom: 54 }}>
            <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
              <span className="pill-badge" style={{ color: '#EF4444', borderColor: '#EF4444' }}>
                ANSWERS & ASSISTANCE
              </span>
            </div>
            <h2 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', fontWeight: 800, color: 'var(--tw-text-white)', marginBottom: 16 }}>
              YouTube Content ID <span style={{ color: '#EF4444' }}>FAQs</span>
            </h2>
            <p style={{ color: 'var(--tw-text-dim)', fontSize: '1.05rem' }}>
              Common questions about claims, whitelisting channels, cover songs, and receiving payments.
            </p>
          </div>

          <div className="reveal-stagger" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
            {CONTENT_ID_FAQS.map((faq, idx) => {
              const isOpen = openFaq === idx;
              return (
                <div 
                  key={idx}
                  className="glass-panel"
                  style={{
                    borderRadius: 16,
                    border: isOpen ? '1px solid rgba(239, 68, 68, 0.35)' : '1px solid rgba(255, 255, 255, 0.08)',
                    background: isOpen ? 'rgba(239, 68, 68, 0.03)' : 'rgba(255, 255, 255, 0.02)',
                    overflow: 'hidden',
                    transition: 'all 0.2s ease'
                  }}
                >
                  <button
                    onClick={() => setOpenFaq(isOpen ? -1 : idx)}
                    style={{
                      width: '100%',
                      padding: '22px 24px',
                      display: 'flex',
                      alignItems: 'center',
                      justifyContent: 'space-between',
                      background: 'none',
                      border: 'none',
                      color: "var(--tw-text-white)",
                      fontSize: '1.05rem',
                      fontWeight: 700,
                      cursor: 'pointer',
                      textAlign: 'left'
                    }}
                  >
                    <span>{faq.q}</span>
                    <ChevronDown 
                      size={20} 
                      style={{
                        transform: isOpen ? 'rotate(180deg)' : 'rotate(0)',
                        transition: 'transform 0.25s ease',
                        color: isOpen ? '#EF4444' : '#64748B',
                        flexShrink: 0,
                        marginLeft: 16
                      }} 
                    />
                  </button>

                  {isOpen && (
                    <div style={{
                      padding: '0 24px 22px',
                      color: 'var(--tw-text-dim)',
                      fontSize: '0.95rem',
                      lineHeight: 1.65,
                      borderTop: '1px solid rgba(255, 255, 255, 0.05)',
                      paddingTop: 16
                    }}>
                      {faq.a}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* 10. BOTTOM CTA STRIP */}
      <section style={{ padding: '60px 0 20px' }}>
        <div className="container">
          <div className="glass-panel card-shimmer-sweep dark-inverted-section" style={{
            borderRadius: 24,
            padding: 'clamp(40px, 6vw, 70px)',
            background: 'radial-gradient(circle at center, rgba(239, 68, 68, 0.15) 0%, rgba(9, 13, 21, 0.98) 100%)',
            border: '1px solid rgba(239, 68, 68, 0.3)',
            textAlign: 'center',
            boxShadow: '0 30px 60px -20px rgba(0,0,0,0.8)'
          }}>
            <h2 style={{
              fontSize: 'clamp(2.2rem, 5vw, 3.6rem)',
              fontWeight: 900,
              lineHeight: 1.15,
              marginBottom: 18,
              color: '#FFFFFF'
            }}>
              Ready to release? <br />
              <span className="text-cyan-gradient">Get started in 60 seconds.</span>
            </h2>

            <p style={{ fontSize: '1.15rem', color: '#CBD5E1', maxWidth: '640px', margin: '0 auto 36px', lineHeight: 1.6 }}>
              Protect every track across YouTube, Spotify, and 150+ stores. Keep 100% of your earnings.
            </p>

            <button 
              onClick={() => onNavigate('/signup')}
              className="btn-cyan"
              style={{
                padding: '18px 44px',
                fontSize: '1.1rem',
                fontWeight: 800,
                background: 'linear-gradient(135deg, var(--tw-cyan) 0%, #007EA7 100%)',
                color: '#090D15',
                border: 'none',
                boxShadow: '0 12px 30px -8px rgba(0, 229, 255, 0.45)'
              }}
            >
              <span>Sign up free</span>
              <ArrowRight size={20} className="btn-icon-hover" />
            </button>
          </div>
        </div>
      </section>
    </div>
  );
}
